
export const BOOKS_LOADED = 'BOOKS_LOADED';
export const BOOKS_REQUESTED = 'BOOKS_REQUESTED';
export const BOOKS_ERROR = 'BOOKS_ERROR';
export const BOOK_ADDED_TO_CART = 'BOOK_ADDED_TO_CART';
export const BOOK_REMOVED_FROM_CART = 'BOOK_REMOVED_FROM_CART'; 
export const ALL_BOOK_REMOVED_FROM_CART = 'ALL_BOOK_REMOVED_FROM_CART'; 